#!/bin/sh
#
# Set commit timestamp to sometging different than current time, e.g. a date offset
#
# Date must be generated by a command stored in GIT_DATEFUNC variable.

function dcommit() {
    if [ -z "$GIT_DATEEFUNC" ]; then
        echo "You must set GIT_DATEFUNC. Example: export GIT_DATEFUNC'date -v-1d' to work yesterday."
    else
        env GIT_AUTHOR_DATE="$(eval $GIT_DATEFUNC)" GIT_COMMITTER_DATE="$(eval $GIT_DATEFUNC)" git commit $*
    fi
}



